In [27]:
import pandas as pd

file_path = '/home/btech/ayush.singh/HSN/tune_diffusion/examples/dreambooth/data.csv'
df = pd.read_csv(file_path)


# Step 3: Filter the DataFrame to select all rows with the desired value
filtered_data = df[df['Dataset_Name'] == 'clock']
filtered_data = filtered_data[filtered_data['diffusion_ver'] == 'sdxl']
sorted_df = filtered_data.sort_values(by='clipi', ascending=False)

# Step 4: Display the filtered data
print(sorted_df)

    Dataset_Name diffusion_ver Adaptor  lora_rank     clipi     clipt  \
350        clock          sdxl   krona          4  0.792969  0.291901
338        clock          sdxl   krona          4  0.788574  0.296038
529        clock          sdxl    lora          8  0.787598  0.300807
763        clock          sdxl    lora          4  0.786133  0.304182
721        clock          sdxl    lora          4  0.785645  0.310861
..           ...           ...     ...        ...       ...       ...
367        clock          sdxl   krona          4  0.708496  0.323530
650        clock          sdxl    lora          8  0.707520  0.282209
618        clock          sdxl   krona          4  0.704590  0.298955
704        clock          sdxl    lora          8  0.680176  0.281499
677        clock          sdxl    lora          8  0.659180  0.275129

     num_train_steps  no_of_images  learning_rate  \
350             1200             6       0.000100
338             1000             6       0.000100
529             1200             6       0.000020
763             1000             6       0.000100
721              400             6       0.000100
..               ...           ...            ...
367              800             6       0.000005
650              800             6       0.000500
618             1000             6       0.000500
704             1200             6       0.000500
677             1000             6       0.000500

                                           output_path  \
350  /home/btech/ayush.singh/outputs_sdxl/clock/kro...
338  /home/btech/ayush.singh/outputs_sdxl/clock/kro...
529  /home/btech/ayush.singh/outputs_sdxl/clock/lor...
763  /home/btech/ayush.singh/outputs_sdxl/clock/lor...
721  /home/btech/ayush.singh/outputs_sdxl/clock/lor...
..                                                 ...
367  /home/btech/ayush.singh/outputs_sdxl/clock/kro...
650  /home/btech/ayush.singh/outputs_sdxl/clock/lor...
618  /home/btech/ayush.singh/outputs_sdxl/clock/kro...
704  /home/btech/ayush.singh/outputs_sdxl/clock/lor...
677  /home/btech/ayush.singh/outputs_sdxl/clock/lor...

     with_prior_preservation
350                    False
338                    False
529                    False
763                    False
721                    False
..                       ...
367                    False
650                    False
618                    False
704                    False
677                    False

[119 rows x 11 columns]

In [31]:
sorted_df = filtered_data.sort_values(by='clipt', ascending=False)
sorted_df

,Dataset_Name,diffusion_ver,Adaptor,lora_rank,clipi,clipt,num_train_steps,no_of_images,learning_rate,output_path,with_prior_preservation
357,clock,sdxl,krona,4,0.726562,0.326826,400,6,0.000005,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False
413,clock,sdxl,krona,4,0.730957,0.326712,1000,6,0.000002,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False
51,clock,sdxl,krona,8,0.729980,0.326486,400,6,0.000005,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False
718,clock,sdxl,krona,16,0.727051,0.326355,800,6,0.000002,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False
120,clock,sdxl,krona,8,0.722656,0.326181,1200,6,0.000002,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False
...,...,...,...,...,...,...,...,...,...,...,...
597,clock,sdxl,krona,4,0.778320,0.293187,400,6,0.000500,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False
350,clock,sdxl,krona,4,0.792969,0.291901,1200,6,0.000100,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False
650,clock,sdxl,lora,8,0.707520,0.282209,800,6,0.000500,/home/btech/ayush.singh/outputs_sdxl/clock/lor...,False
704,clock,sdxl,lora,8,0.680176,0.281499,1200,6,0.000500,/home/btech/ayush.singh/outputs_sdxl/clock/lor...,False
677,clock,sdxl,lora,8,0.659180,0.275129,1000,6,0.000500,/home/btech/ayush.singh/outputs_sdxl/clock/lor...,False

In [32]:
columns_to_normalize = ['clipi', 'clipt']
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
sorted_df[columns_to_normalize] = scaler.fit_transform(sorted_df[columns_to_normalize])

# Step 4: Calculate a new column 'Normalised' by summing the normalized values of the selected columns
sorted_df['Normalised'] = sorted_df[columns_to_normalize].sum(axis=1)

# Step 5: Sort the DataFrame based on the 'Normalised' column in descending order
sorted_df = sorted_df.sort_values(by='Normalised', ascending=False)

# Step 6: Display the sorted DataFrame
print(sorted_df['Normalised'])

721    1.636434
413    1.534304
51     1.522619
763    1.510889
357    1.503650
         ...
308    0.967864
618    0.800286
650    0.498268
704    0.280142
677    0.000000
Name: Normalised, Length: 119, dtype: float64

In [42]:
df_new= sorted_df.sort_values(by='Normalised', ascending=False).head(20)

In [43]:
df_new

,Dataset_Name,diffusion_ver,Adaptor,lora_rank,clipi,clipt,num_train_steps,no_of_images,learning_rate,output_path,with_prior_preservation,Normalised
721,clock,sdxl,lora,4,0.945255,0.691179,400,6,0.000100,/home/btech/ayush.singh/outputs_sdxl/clock/lor...,False,1.636434
413,clock,sdxl,krona,4,0.536496,0.997807,1000,6,0.000002,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.534304
51,clock,sdxl,krona,8,0.529197,0.993422,400,6,0.000005,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.522619
763,clock,sdxl,lora,4,0.948905,0.561983,1000,6,0.000100,/home/btech/ayush.singh/outputs_sdxl/clock/lor...,False,1.510889
357,clock,sdxl,krona,4,0.503650,1.000000,400,6,0.000005,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.503650
718,clock,sdxl,krona,16,0.507299,0.990892,800,6,0.000002,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.498191
435,clock,sdxl,krona,4,0.536496,0.958678,400,6,0.000001,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.495174
173,clock,sdxl,krona,8,0.649635,0.843819,800,6,0.000050,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.493454
90,clock,sdxl,krona,8,0.536496,0.952606,400,6,0.000002,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.489102
99,clock,sdxl,krona,8,0.514599,0.972002,800,6,0.000002,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.486601
471,clock,sdxl,krona,4,0.510949,0.973183,1200,6,0.000001,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.484132
128,clock,sdxl,krona,8,0.529197,0.954630,400,6,0.000001,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.483827
148,clock,sdxl,krona,8,0.536496,0.943835,1000,6,0.000001,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.480332
138,clock,sdxl,krona,8,0.547445,0.932029,800,6,0.000001,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.479474
453,clock,sdxl,krona,4,0.521898,0.955642,1000,6,0.000001,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.477540
429,clock,sdxl,krona,4,0.500000,0.973014,1200,6,0.000002,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.473014
161,clock,sdxl,krona,8,0.514599,0.956148,1200,6,0.000001,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.470746
758,clock,sdxl,krona,16,0.521898,0.948389,800,6,0.000001,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.470287
782,clock,sdxl,krona,16,0.503650,0.960870,1200,6,0.000001,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.464520
110,clock,sdxl,krona,8,0.496350,0.966436,1000,6,0.000002,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.462787

krona_sdxl_8_0.0005_800_False